cve fixes 24 march 2022
hmcts/bar-api pull request #521
Opened 2022-03-24 10:26 UTC by larslunde-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-24 16:56 UTC, PragneshPatel2 requested changes
Could you please update date to 2022-06-30 for all CVE.

2022-03-24 17:02 UTC, PragneshPatel2 submitted a review, later dismissed

2022-04-08 09:31 UTC, anoojhmcts approved these changes

2022-04-08 09:37 UTC, kaushikmaitra approved these changes

2022-04-08 09:43 UTC, anshikanigam15 approved these changes

2022-04-08 10:27 UTC, santu412 approved these changes

2022-04-08 10:29 UTC, merged